default_platform(:ios)

platform :ios do
  desc "Runs unit tests"
  lane :tests do
    run_tests(
      package_path: '.',
      scheme: 'RqesKit',
      devices: [ENV.fetch('TEST_DEVICE', 'iPhone Air')],
      result_bundle: true,
      xcargs: '-skipPackagePluginValidation -skipMacroValidation'
    )
  end
end
